name: Playwright Tests using docker and sharding
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SHARD: [1, 2, 3]
        NUM_SHARDS: [3]
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Run Playwright tests
        run: pnpm exec playwright test --shard ${{ matrix.SHARD }}/${{ matrix.NUM_SHARDS }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.SHARD }}
          path: playwright-report/
          retention-days: 30
